version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: container_integrador1_grupo13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: db_integrador_1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: